Update acf-core_de.properties (#425)
* Update acf-core_de.properties

Changed acf-core.please_specify_at_least from:
Error: Bitte gib eine Zahl größer oder gleich {min} ein.

To:
Fehler: Bitte gib eine Zahl größer oder gleich {min} ein.

* Update acf-core_de.properties

Changed acf-core.please_specify_at_least so it matches the other messages from:
Error: Bitte gib eine Zahl größer oder gleich {min} ein.

To:
Fehler: Bitte gib eine Zahl größer oder gleich {min} ein.